# Generated by Django 2.1.2 on 2018-10-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0002_devicemodel_taskmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_devToken', models.CharField(max_length=128)),
                ('wx_bind_date', models.DateField()),
                ('wx_userName', models.CharField(max_length=125)),
            ],
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='task_crt_date',
            new_name='task_cr_date',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='task_fish_date',
            new_name='task_sh_date',
        ),
    ]
