# Generated by Django 2.1.2 on 2018-10-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0003_auto_20181031_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='app_ver',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='dev_name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='dev_sdk',
            field=models.CharField(max_length=48),
        ),
    ]
