# Generated by Django 2.1.2 on 2018-10-31 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0004_auto_20181031_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='dev_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
