# Generated by Django 2.1.2 on 2018-10-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0005_devicemodel_dev_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='dev_andId',
            new_name='dev_token',
        ),
    ]
