# Generated by Django 2.1.2 on 2018-11-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0006_auto_20181031_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wxUserModel',
        ),
    ]
