# Generated by Django 2.1.2 on 2018-11-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0007_delete_wxusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='dev_date',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_cr_date',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_sh_date',
            field=models.CharField(max_length=48),
        ),
    ]
