# Generated by Django 2.1.2 on 2018-11-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0009_auto_20181101_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_type',
            field=models.CharField(max_length=20),
        ),
    ]
