# Generated by Django 2.1.2 on 2018-11-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0010_auto_20181101_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='dev_imei',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_cr_date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_sh_date',
            field=models.CharField(max_length=64),
        ),
    ]
