# Generated by Django 2.1.2 on 2018-11-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_android', '0011_auto_20181102_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_desc',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
