# Generated by Django 2.1.2 on 2018-11-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_wx', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wxUserModel',
            new_name='UserModel',
        ),
    ]
