# Generated by Django 2.1.2 on 2018-11-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_wx', '0003_auto_20181101_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wx_appId',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
