# Generated by Django 2.1.2 on 2018-11-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_wx', '0004_usermodel_wx_appid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='wx_appId',
            field=models.CharField(max_length=124),
        ),
    ]
