# Generated by Django 2.1.2 on 2018-11-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpush_wx', '0005_auto_20181108_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wx_bindAccount',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='wx_bindpwd',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
