"""
Django settings for momoxiaoming_django project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os






# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i#7ce-7z@av7!#^a6&n79#7@jb7opf396zh93)rmdu4v0p*y8j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True




ALLOWED_HOSTS = [
    '*',
]


# Application definition

INSTALLED_APPS = [
    "ddpush_wx.apps.DdpushWxConfig",  # 添加自己应用
    "ddpush_android.apps.DingdingpushConfig",    #添加自己应用
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',  #定时任务
    'djcelery',   #定时任务
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  #全局禁用对post接口进行安全验证
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'momoxiaoming_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'momoxiaoming_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

    #服务器
    'default': {
        'ENGINE': 'django.db.backends.mysql',   #mysql 驱动
        'NAME': 'ddpush',   #数据库名称
        'USER': 'xx',
        'PASSWORD': 'xxx',
        'HOST': 'xxx',
        'PORT': 'xx',
    }

  
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'  #这里要换成上海东八区的时间,否者会延后8小时

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = False   #去除网址后面默认加 /

# Static files (CSS, JavaScript, Images),
# https://docs.djangoproject.com/en/2.1/howto/static-files/
# 查找器,查找全局目录下static文件夹
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = '/static/'

# 定时任务配置
CRONJOBS = [
    # 表示每分钟执行
    ('*/1 * * * *', 'ddpush_wx.DsTask.task','>>/data/web/log/DsTask_task.log'),
    # ('*/1 * * * *', 'ddpush_wx.DsTask.test', '>>/Users/zhangxiaoming/test.log')

]


# djcelery 定时任务配置
import djcelery
djcelery.setup_loader()
# BROKER_URL = 'redis://127.0.0.1:6379/6'
CELERY_IMPORTS = ('ddpush_wx.DsTask', )
CELERY_TIMEZONE = TIME_ZONE
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

# 下面是定时任务的设置，我一共配置了三个定时任务.
from celery.schedules import crontab
CELERYBEAT_SCHEDULE = {
    #定时任务一：　每24小时周期执行任务(del_redis_data)
    u'定时执行任务': {
        "task": "ddpush_wx.DsTask.task",
        "schedule": crontab(minute='*/1'),
        "args": (),
    },
}
